format = """
$username @ $localip $os  in $directory $all"""

[os]
disabled=false
format = '[$symbol](green)'

[os.symbols]
Alpine = "ğŸ”ï¸"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Gentoo = "ğŸ—œï¸"
Kali = "ğŸ‰"
Linux = "ğŸ§"
Macos = "ğŸ"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "â„ï¸"
OpenBSD = "ğŸ¡"
openSUSE = "ğŸ¦ "
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
Ubuntu = "ğŸ¯"
Windows = "ğŸªŸ"

[character]
success_symbol = "[ âŸ ](bold blue)" 
error_symbol = "[âœ–](bold red) "

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"
discharging_symbol = "âš¡"
charging_symbol = "ğŸ”Œ"
[[battery.display]]
threshold = 99
style = "yellow"
discharging_symbol = "âš¡"
charging_symbol = "ğŸ”Œ"
[[battery.display]]
threshold = 100
discharging_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”‹"

[c]
format = "via [$name $version]($style)"
[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[memory_usage]
threshold = 50
symbol = "ó°“…"
style = "bold dimmed white"
format = '([$symbol( ${ram})]($style))'
disabled = false

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[localip]
ssh_only = false
format = '[$localipv4](#FFC0CB)'
disabled = false
